In [48]:
import numpy as np
array_ventas = []

In [49]:
def generar_datos_ventas(productos, tiendas, dias):
  return np.random.randint(0, 100, size=(productos, tiendas, dias))

In [50]:

array_ventas = generar_datos_ventas(10,5,7)

print("Array de ventas generado:")
print(array_ventas)

Array de ventas generado:
[[[71 92 95 73  6 65 49]
  [87 45 94 89  8 32 88]
  [66 46 46 48 30 60 37]
  [91  8 79 43 36 61  5]
  [ 0  2 18  5 20  3  9]]

 [[89 81  2 90 74 96 57]
  [83 88 79 63 79 31 37]
  [14 44 54 71 67 36 70]
  [37  7 35 57 80 51 45]
  [97 72 45 18 90 57 33]]

 [[12 43 53 48 22 39 87]
  [77 98 53  2 15 85 93]
  [92 12  8 91 99 76 82]
  [64  7 22 85 29 76 38]
  [24 21 80 71 96 59 95]]

 [[47 95 97  8 87 24 11]
  [93 60 87 17 27 22 19]
  [51 53 98 89 23 92 27]
  [14 29 78 84 97 34 41]
  [71 27 27 61  8 76 96]]

 [[54 15 78 63 20 96 39]
  [47 19 99 62 96 96 65]
  [30 72 71 94 67  4 94]
  [92 69 18 23 32 87 86]
  [44 92 41 35 23 87 67]]

 [[73 96  7 76 77 60 82]
  [19 97 27 33 20 84 89]
  [11  4 91 33 95 79 20]
  [21 70 58 81 42 98 51]
  [94 10 75 68 62 72 29]]

 [[ 1 15 21 11 24 81 50]
  [94 23 61 74 32 59  2]
  [97  2 92 86 37 61 83]
  [25 10 88 44 18 30 80]
  [17 77 25 31 63  7 29]]

 [[34 20 59 87  1 26 70]
  [45 54 93 37 77 33 93]
  [87 83 74 31 69 61 88]
  [10 77 8

In [51]:
def calcular_totales_ventas_por_producto(datos):
  totales_por_producto = np.sum(datos, axis=(1, 2))
 # print(totales_por_producto)
  return totales_por_producto

In [52]:
def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

In [53]:
def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(1, 2))

In [54]:
def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 2))

In [55]:

def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

In [56]:
def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas


In [57]:
def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas


In [59]:
totales_por_producto = calcular_totales_ventas_por_producto(array_ventas)
totales_por_tienda = calcular_totales_ventas_por_tienda(array_ventas)
promedio_por_producto = calcular_promedio_ventas_por_producto(array_ventas)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(array_ventas)
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)


# Imprime los resultados
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")

Total de ventas por producto a lo largo de la semana: [1607 2029 1954 1870 2077 2004 1550 1861 1464 1886]
Total de ventas por tienda a lo largo de la semana: [3648 4062 3920 3353 3319]
Promedio de ventas por producto por día: [45.91428571 57.97142857 55.82857143 53.42857143 59.34285714 57.25714286
 44.28571429 53.17142857 41.82857143 53.88571429]
Promedio de ventas por tienda por día: [52.11428571 58.02857143 56.         47.9        47.41428571]
Producto con mayor ventas: Producto 4
Producto con menor ventas: Producto 8
Tienda con mayor ventas: Tienda 1
Tienda con menor ventas: Tienda 4
